### ISSUE TITLE
How to monitor number of members eligible for primary?

### ISSUE THREAD

**Issue by hiroshi** [percona/mongodb_exporter#292]
Is it a way to count the number of members eligible for primary?

I'm not sure, but to get the information, priority and hidden of replSetGetConfig is needed.
https://docs.mongodb.com/manual/reference/command/replSetGetConfig/#mongodb-dbcommand-dbcmd.replSetGetConfig
However replSetGetConfig is not the list at v0.20.5.

Or anythink alike in the current set of metrics?

Thanks in advance.

**Comment by percona-csalguero** [comment]
Hello, 

I am not a MongoDB expert but as a developer being done some work in a backup tool for MongoDB I can tell you hidden servers are not elegible to become primary. Because of that, the backup tools search for hidden servers to use as the backup source since reading them won't affect the client's performance. 
Priority IS taken into account and probably `arbiterOnly` too. 

Regards.

**Comment by hiroshi** [comment]
Hi @percona-csalguero,
Thanks for your attention.

Sorry for my vague question. I meant to ask it in the context of percona/mongodb_exporter.

So, my question is:
Using percona/mongodb_exporter, Is it a way to tell that primary eligible members are more than one?

Anyway, I was starting to extend percona/mongodb_exporter. Make it get those information with replSetGetConfig.
I'll create a PR when it works.
