### ISSUE TITLE
Any way of setting poll interval?

### ISSUE THREAD

**Issue by wildone** [percona/mongodb_exporter#309]
Love the exporter, would love to see if there is poll interval setting?

**Comment by denisok** [comment]
Hi Max,

what do you mean by poll interval? As I understand it - this exporter implements standard Prometheus exporter with help of it's client lib:
https://prometheus.io/docs/instrumenting/writing_exporters/

And that is based on `scrape_interval` on how often Collector is called to get metrics.
https://prometheus.io/docs/introduction/first_steps/#configuring-prometheus

Thanks,
Denys

**Comment by ygormutti** [comment]
If I understood the code correctly, the exporter issues MongoDB commands to collect metrics during `/metrics` request handling, so you can control the poll interval from your Prometheus job configuration.

Despite being super simple, this approach have cause us some issues. In our case, the existing prometheus job had a 10s timeout, which was insufficient sometimes. We had to create a new Prometheus job with increased `scrape_timeout` and `scrape_interval`. Still, there is a lot of discontinuity in our MongoDB metrics, because some mongo commands are failing sometimes and I suppose the exporter doesn't store the results of previous command runs (right?).

![image](https://user-images.githubusercontent.com/114103/126509648-853f5847-9636-4510-a9f5-57a621a176c5.png)

Maybe if metrics collecting and `/metrics` request handling were concurrent there would be less issues.

**Comment by denisok** [comment]
Hi @ygormutti,

this exporter based on standard lib with some additional features (tls and etc). But it is implementing standard practice:
https://prometheus.io/docs/instrumenting/writing_exporters/#collectors
https://prometheus.io/docs/instrumenting/writing_exporters/#scheduling

We use standard github.com/prometheus/client_golang fo it.

There could be caches for sure:
https://prometheus.io/docs/practices/instrumentation/#caches
https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics

Could you provide some logs for the exporter to see why it fails and what is going on, maybe there is some other issue that we need to fix?

I am adding @percona-csalguero as he knows much more than I.

Thanks,
Denys

**Comment by percona-csalguero** [comment]
As mentioned by @ygormutti all exporters, not only the MongoDB exporter collect metrics on request.
There is no poll interval concept in the exporters. The polling interval is how often Prometheus (or any other gatherer) pulls the metrics from the exporter's HTTP interface.

**Comment by ygormutti** [comment]
> Could you provide some logs for the exporter to see why it fails and what is going on, maybe there is some other issue that we need to fix?

@denisok thanks for asking. It seems to be a network issue because it doesn't happen in all hosts and this issue (now closed) is a bit off-topic, but here are the logs from 3 scrapes, anyway:

```
time="2021-07-22T18:04:08Z" level=warning msg="cannot create metrics for oplog: connection(hulk2:19000[-774]) incomplete read of full message: context canceled"
time="2021-07-22T18:04:08Z" level=error msg="Cannot get node type to check if this is a mongos: context canceled"
time="2021-07-22T18:04:08Z" level=error msg="cannot get replSetGetStatus: context canceled"
time="2021-07-22T18:04:08Z" level=error msg="cannot run getDiagnosticData: context canceled"
time="2021-07-22T18:04:08Z" level=error msg="error while checking mongodb connection: context canceled. mongo_up is set to 0"
time="2021-07-22T18:04:08Z" level=error msg="cannot get replSetGetStatus: context canceled"
time="2021-07-22T18:07:08Z" level=warning msg="cannot create metrics for oplog: connection(hulk2:19000[-776]) failed to write: context canceled"
time="2021-07-22T18:07:08Z" level=error msg="Cannot get node type to check if this is a mongos: connection(hulk2:19000[-776]) failed to write: context canceled"
time="2021-07-22T18:07:08Z" level=error msg="cannot get replSetGetStatus: connection(hulk2:19000[-776]) failed to write: context canceled"
time="2021-07-22T18:07:08Z" level=error msg="cannot get replSetGetStatus: connection(hulk2:19000[-776]) failed to write: context canceled"
time="2021-07-22T18:07:08Z" level=error msg="error while checking mongodb connection: connection(hulk2:19000[-775]) failed to write: context canceled. mongo_up is set to 0"
time="2021-07-22T18:07:08Z" level=error msg="cannot run getDiagnosticData: connection(hulk2:19000[-776]) failed to write: context canceled"
time="2021-07-22T18:11:08Z" level=warning msg="cannot create metrics for oplog: connection(hulk2:19000[-775]) failed to write: context canceled"
time="2021-07-22T18:11:08Z" level=error msg="Cannot get node type to check if this is a mongos: connection(hulk2:19000[-775]) failed to write: context canceled"
time="2021-07-22T18:11:08Z" level=error msg="cannot get replSetGetStatus: connection(hulk2:19000[-775]) failed to write: context canceled"
time="2021-07-22T18:11:08Z" level=error msg="cannot get replSetGetStatus: connection(hulk2:19000[-775]) failed to write: context canceled"
time="2021-07-22T18:11:08Z" level=error msg="cannot run getDiagnosticData: connection(hulk2:19000[-775]) failed to write: context canceled"
time="2021-07-22T18:11:08Z" level=error msg="error while checking mongodb connection: connection(hulk2:19000[-775]) failed to write: context canceled. mongo_up is set to 0"
time="2021-07-22T18:15:08Z" level=warning msg="cannot create metrics for oplog: connection(hulk2:19000[-779]) failed to write: context canceled"
time="2021-07-22T18:15:08Z" level=error msg="Cannot get node type to check if this is a mongos: connection(hulk2:19000[-779]) failed to write: context canceled"
```
On a second though, returning cached results from last scrape in case of fail doesn't seem a good idea, because it will probably cause false positives in alerting systems.

However, the exporter log messages were generic and didn't help much. Do you think it's worth a new issue?

**Comment by denisok** [comment]
I am guessing those messages are from mongo driver and has nothing to do with the exporter, maybe there is a way to pass some `debug` flag or enable debug log level to get more useful info.

As for failed scrapes:
https://prometheus.io/docs/instrumenting/writing_exporters/#failed-scrapes

I think it is also up to monitoring agent, how it is configured on what data to push or how indicate in DB that scrape has failed so it will be visible somehow on the graphic, but no data is no data and it is fair without connection to DB.

**Comment by percona-csalguero** [comment]
Those messages an be caused by a different problem, maybe because the server is a mongos or a standalone like in https://github.com/percona/mongodb_exporter/issues/296.
Anyway, feel free to open a new issue with more information so we can reproduce it.
If you can provide more context information, I could write a new test for this case.

Regards

**Comment by ygormutti** [comment]
> Those messages an be caused by a different problem, maybe because the server is a mongos or a standalone like in #296.

Unfortunately, these logs comes from a replica set with three data-bearing nodes.

> Anyway, feel free to open a new issue with more information so we can reproduce it.
> If you can provide more context information, I could write a new test for this case.

Thanks, but the only way I can reproduce this is connecting to some nodes from different networks. Example: exporter for hulk2 running on gcloud fails, while on local ISP it works flawlessly; exporter for hulk3 works fine running from both networks. :confused: Sound like networking issue to me.

**Comment by percona-csalguero** [comment]
I know it is a hack and not a real solution but, have you tried to increase the [timeout options](https://docs.mongodb.com/manual/reference/connection-string/#timeout-options) in the URI?
