### ISSUE TITLE
Commandline switch `--web.telemetry-path` seems not wrking

### ISSUE THREAD

**Issue by mmafshari77** [percona/mongodb_exporter#541]
No matter which value I provide in the commandline for `--web.telemetry-path` switch, the web page is just accessible at `/metrics` url.
Another problem related to this problem is that the `/` path returns `404 not found` status code which is not like other prometheus exporters -- other prom exporters return a `202` status code at the `/` url and some information about the exporter itself.

**Comment by a-gavin** [comment]
[This line](https://github.com/percona/mongodb_exporter/blob/5c3358c3bab3823588fb801a84f3eb7985d2765c/exporter/exporter.go#L328) is likely to blame for the `--web.telemetry-path` issue. Should be referencing [this field](https://github.com/percona/mongodb_exporter/blob/5c3358c3bab3823588fb801a84f3eb7985d2765c/exporter/exporter.go#L104) instead of hardcoding `"/metrics"`. Can't speak to the other issue.
